// <auto-generated />
using EncryptionSoftware.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EncryptionSoftware.Persistence.Migrations
{
    [DbContext(typeof(EncryptionSoftwareContext))]
    [Migration("20220930192856_Se Modifica la entidad Frases")]
    partial class SeModificalaentidadFrases
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EncryptionSoftware.Domain.Frases", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Clave")
                        .HasColumnType("integer");

                    b.Property<string>("Frase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Frases");
                });

            modelBuilder.Entity("EncryptionSoftware.Domain.Productos", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Iva")
                        .HasColumnType("integer");

                    b.Property<string>("ListaDePrecios")
                        .HasColumnType("text");

                    b.Property<bool>("ProductoParaLaVenta")
                        .HasColumnType("boolean");

                    b.HasKey("Codigo");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Codigo = 1,
                            Descripcion = "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
                            Imagen = "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
                            Iva = 19,
                            ListaDePrecios = "[]",
                            ProductoParaLaVenta = true
                        },
                        new
                        {
                            Codigo = 2,
                            Descripcion = "Mens Casual Premium Slim Fit T-Shirts",
                            Imagen = "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
                            Iva = 19,
                            ListaDePrecios = "[]",
                            ProductoParaLaVenta = true
                        },
                        new
                        {
                            Codigo = 3,
                            Descripcion = "Mens Cotton Jacket",
                            Imagen = "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
                            Iva = 19,
                            ListaDePrecios = "[5000]",
                            ProductoParaLaVenta = true
                        },
                        new
                        {
                            Codigo = 4,
                            Descripcion = "Mens Casual Slim Fit",
                            Imagen = "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
                            Iva = 19,
                            ListaDePrecios = "[50000]",
                            ProductoParaLaVenta = true
                        },
                        new
                        {
                            Codigo = 5,
                            Descripcion = "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
                            Imagen = "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
                            Iva = 19,
                            ListaDePrecios = "[50400]",
                            ProductoParaLaVenta = true
                        },
                        new
                        {
                            Codigo = 6,
                            Descripcion = "Solid Gold Petite Micropave",
                            Imagen = "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
                            Iva = 19,
                            ListaDePrecios = "[4500]",
                            ProductoParaLaVenta = true
                        },
                        new
                        {
                            Codigo = 7,
                            Descripcion = "White Gold Plated Princess",
                            Imagen = "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
                            Iva = 19,
                            ListaDePrecios = "[95000]",
                            ProductoParaLaVenta = true
                        },
                        new
                        {
                            Codigo = 8,
                            Descripcion = "Pierced Owl Rose Gold Plated Stainless Steel Double",
                            Imagen = "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
                            Iva = 19,
                            ListaDePrecios = "[36800]",
                            ProductoParaLaVenta = true
                        },
                        new
                        {
                            Codigo = 9,
                            Descripcion = "WD 2TB Elements Portable External Hard Drive - USB 3.0",
                            Imagen = "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
                            Iva = 19,
                            ListaDePrecios = "[89000]",
                            ProductoParaLaVenta = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
